### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hlldhy** [FedericoComoglio/wavClusteR#10] opened 2023-04-01 11:29 UTC
when I run this,I get this error 
![image](https://user-images.githubusercontent.com/102451304/229286017-eba52da4-ce65-4660-8a3a-c684f8943477.png)
![image](https://user-images.githubusercontent.com/102451304/229286024-edcf86a0-4fff-49f5-a513-b8234cfbec4c.png)
But I check my Bam data,there is no NA in data ,I don't know how?  would you help me? Thanks !

**Comment by csdaw** [comment] 2023-06-26 15:35
Hi there,

I'm getting the same error. I've narrowed the cause down to a bug in this line of the `wavClusteR:::processChunk` function.

https://github.com/FedericoComoglio/wavClusteR/blob/2c75c300a7d8e4a1019ceb4be9ac5fa6a311354d/R/processMD.R#L96

It occurs when your BAM file reads have MD tags that contain the deletion character `^` e.g. an example from my data `15^AT1T38`. I'm may attempt to fix it soon. Or a slightly poor solution is to remove any read with a deletion with respect the reference genome.

**Comment by FedericoComoglio** [comment] 2023-10-11 07:05
Thank you for reporting and apologies for such a late reply. This project is no longer active. @csdaw pinpointed the root cause correctly, wavClusteR does not accept BAM files that contain INDELs in the MD tag. I'm closing this issue, but you are welcome to contribute a feature extending `processMD` to work with INDELs.

**Closed as completed by FedericoComoglio** 2023-10-11 07:05 UTC

**Comment by santataRU** [comment] 2025-08-11 19:00
> Hi there,
> 
> I'm getting the same error. I've narrowed the cause down to a bug in this line of the `wavClusteR:::processChunk` function.
> 
> [wavClusteR/R/processMD.R](https://github.com/FedericoComoglio/wavClusteR/blob/2c75c300a7d8e4a1019ceb4be9ac5fa6a311354d/R/processMD.R#L96)
> 
> Line 96 in [2c75c30](/FedericoComoglio/wavClusteR/commit/2c75c300a7d8e4a1019ceb4be9ac5fa6a311354d)
> 
>  mismatchedPos <- cumsum(splitAsList(mismatchedPos, grp))[isCharGrp] 
> It occurs when your BAM file reads have MD tags that contain the deletion character `^` e.g. an example from my data `15^AT1T38`. I'm may attempt to fix it soon. Or a slightly poor solution is to remove any read with a deletion with respect the reference genome.

Dear CSDAW,

I am experiencing the same issue and was wondering if you have found a way to fix the bug.

Best regards,
Xiao

**Comment by santataRU** [comment] 2025-08-11 20:09
My case generates similar error messages below:

Error in .new_IRanges_from_start_end(start, end) :

 'start' or 'end' cannot contain NAs
Warning messages:
1: In min(X[fit$classification == 2]) :
  no non-missing arguments to min; returning Inf


However,  I believe my case is different from the example discussed there. I used Bowtie 1, which is an ungapped aligner and does not generate MD tags with deletions, as it does not support insertions or deletions (indels) in its alignments. I also checked with samtools view and did not find any deletions in my MD tags.


samtools view CLIP91BC4_hg38_m1.sorted.bam \

| awk '{

  for(i=12;i<=NF;i++){if($i ~ /^MD:Z:/){md=$i; sub(/^MD:Z:/,"",md); if(md ~ /\^/){c++} break}}

} END{print c+0}'

0
